package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AllocateSId generated by hbm2java
 */
public class AllocateSId  implements java.io.Serializable {


     private String idOw;
     private int idSec;
     private Date dateStartS;

    public AllocateSId() {
    }

    public AllocateSId(String idOw, int idSec, Date dateStartS) {
       this.idOw = idOw;
       this.idSec = idSec;
       this.dateStartS = dateStartS;
    }
   
    public String getIdOw() {
        return this.idOw;
    }
    
    public void setIdOw(String idOw) {
        this.idOw = idOw;
    }
    public int getIdSec() {
        return this.idSec;
    }
    
    public void setIdSec(int idSec) {
        this.idSec = idSec;
    }
    public Date getDateStartS() {
        return this.dateStartS;
    }
    
    public void setDateStartS(Date dateStartS) {
        this.dateStartS = dateStartS;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AllocateSId) ) return false;
		 AllocateSId castOther = ( AllocateSId ) other; 
         
		 return ( (this.getIdOw()==castOther.getIdOw()) || ( this.getIdOw()!=null && castOther.getIdOw()!=null && this.getIdOw().equals(castOther.getIdOw()) ) )
 && (this.getIdSec()==castOther.getIdSec())
 && ( (this.getDateStartS()==castOther.getDateStartS()) || ( this.getDateStartS()!=null && castOther.getDateStartS()!=null && this.getDateStartS().equals(castOther.getDateStartS()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdOw() == null ? 0 : this.getIdOw().hashCode() );
         result = 37 * result + this.getIdSec();
         result = 37 * result + ( getDateStartS() == null ? 0 : this.getDateStartS().hashCode() );
         return result;
   }   


}


