package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AllocateO generated by hbm2java
 */
public class AllocateO  implements java.io.Serializable {


     private AllocateOId id;
     private Office office;
     private Owner owner;
     private Date dateEndO;
     private String statusO;

    public AllocateO() {
    }

	
    public AllocateO(AllocateOId id, Office office, Owner owner) {
        this.id = id;
        this.office = office;
        this.owner = owner;
    }
    public AllocateO(AllocateOId id, Office office, Owner owner, Date dateEndO, String statusO) {
       this.id = id;
       this.office = office;
       this.owner = owner;
       this.dateEndO = dateEndO;
       this.statusO = statusO;
    }
   
    public AllocateOId getId() {
        return this.id;
    }
    
    public void setId(AllocateOId id) {
        this.id = id;
    }
    public Office getOffice() {
        return this.office;
    }
    
    public void setOffice(Office office) {
        this.office = office;
    }
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }
    public Date getDateEndO() {
        return this.dateEndO;
    }
    
    public void setDateEndO(Date dateEndO) {
        this.dateEndO = dateEndO;
    }
    public String getStatusO() {
        return this.statusO;
    }
    
    public void setStatusO(String statusO) {
        this.statusO = statusO;
    }




}


