package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AllocateCId generated by hbm2java
 */
public class AllocateCId  implements java.io.Serializable {


     private int idC;
     private String idOw;
     private Date dateStartC;

    public AllocateCId() {
    }

    public AllocateCId(int idC, String idOw, Date dateStartC) {
       this.idC = idC;
       this.idOw = idOw;
       this.dateStartC = dateStartC;
    }
   
    public int getIdC() {
        return this.idC;
    }
    
    public void setIdC(int idC) {
        this.idC = idC;
    }
    public String getIdOw() {
        return this.idOw;
    }
    
    public void setIdOw(String idOw) {
        this.idOw = idOw;
    }
    public Date getDateStartC() {
        return this.dateStartC;
    }
    
    public void setDateStartC(Date dateStartC) {
        this.dateStartC = dateStartC;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AllocateCId) ) return false;
		 AllocateCId castOther = ( AllocateCId ) other; 
         
		 return (this.getIdC()==castOther.getIdC())
 && ( (this.getIdOw()==castOther.getIdOw()) || ( this.getIdOw()!=null && castOther.getIdOw()!=null && this.getIdOw().equals(castOther.getIdOw()) ) )
 && ( (this.getDateStartC()==castOther.getDateStartC()) || ( this.getDateStartC()!=null && castOther.getDateStartC()!=null && this.getDateStartC().equals(castOther.getDateStartC()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdC();
         result = 37 * result + ( getIdOw() == null ? 0 : this.getIdOw().hashCode() );
         result = 37 * result + ( getDateStartC() == null ? 0 : this.getDateStartC().hashCode() );
         return result;
   }   


}


