package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AllocateH generated by hbm2java
 */
public class AllocateH  implements java.io.Serializable {


     private AllocateHId id;
     private Hostess hostess;
     private Owner owner;
     private Date dateEndH;
     private String statusH;

    public AllocateH() {
    }

	
    public AllocateH(AllocateHId id, Hostess hostess, Owner owner) {
        this.id = id;
        this.hostess = hostess;
        this.owner = owner;
    }
    public AllocateH(AllocateHId id, Hostess hostess, Owner owner, Date dateEndH, String statusH) {
       this.id = id;
       this.hostess = hostess;
       this.owner = owner;
       this.dateEndH = dateEndH;
       this.statusH = statusH;
    }
   
    public AllocateHId getId() {
        return this.id;
    }
    
    public void setId(AllocateHId id) {
        this.id = id;
    }
    public Hostess getHostess() {
        return this.hostess;
    }
    
    public void setHostess(Hostess hostess) {
        this.hostess = hostess;
    }
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }
    public Date getDateEndH() {
        return this.dateEndH;
    }
    
    public void setDateEndH(Date dateEndH) {
        this.dateEndH = dateEndH;
    }
    public String getStatusH() {
        return this.statusH;
    }
    
    public void setStatusH(String statusH) {
        this.statusH = statusH;
    }




}


