package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AllocateS generated by hbm2java
 */
public class AllocateS  implements java.io.Serializable {


     private AllocateSId id;
     private Secretary secretary;
     private Owner owner;
     private Date dateEndS;
     private String statusS;

    public AllocateS() {
    }

	
    public AllocateS(AllocateSId id, Secretary secretary, Owner owner) {
        this.id = id;
        this.secretary = secretary;
        this.owner = owner;
    }
    public AllocateS(AllocateSId id, Secretary secretary, Owner owner, Date dateEndS, String statusS) {
       this.id = id;
       this.secretary = secretary;
       this.owner = owner;
       this.dateEndS = dateEndS;
       this.statusS = statusS;
    }
   
    public AllocateSId getId() {
        return this.id;
    }
    
    public void setId(AllocateSId id) {
        this.id = id;
    }
    public Secretary getSecretary() {
        return this.secretary;
    }
    
    public void setSecretary(Secretary secretary) {
        this.secretary = secretary;
    }
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }
    public Date getDateEndS() {
        return this.dateEndS;
    }
    
    public void setDateEndS(Date dateEndS) {
        this.dateEndS = dateEndS;
    }
    public String getStatusS() {
        return this.statusS;
    }
    
    public void setStatusS(String statusS) {
        this.statusS = statusS;
    }




}


