package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AllocateC generated by hbm2java
 */
public class AllocateC  implements java.io.Serializable {


     private AllocateCId id;
     private Car car;
     private Owner owner;
     private Date dateEndC;
     private String statusC;

    public AllocateC() {
    }

	
    public AllocateC(AllocateCId id, Car car, Owner owner) {
        this.id = id;
        this.car = car;
        this.owner = owner;
    }
    public AllocateC(AllocateCId id, Car car, Owner owner, Date dateEndC, String statusC) {
       this.id = id;
       this.car = car;
       this.owner = owner;
       this.dateEndC = dateEndC;
       this.statusC = statusC;
    }
   
    public AllocateCId getId() {
        return this.id;
    }
    
    public void setId(AllocateCId id) {
        this.id = id;
    }
    public Car getCar() {
        return this.car;
    }
    
    public void setCar(Car car) {
        this.car = car;
    }
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }
    public Date getDateEndC() {
        return this.dateEndC;
    }
    
    public void setDateEndC(Date dateEndC) {
        this.dateEndC = dateEndC;
    }
    public String getStatusC() {
        return this.statusC;
    }
    
    public void setStatusC(String statusC) {
        this.statusC = statusC;
    }




}


