package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AllocateOId generated by hbm2java
 */
public class AllocateOId  implements java.io.Serializable {


     private String idOw;
     private long codeO;
     private Date dateStartO;

    public AllocateOId() {
    }

    public AllocateOId(String idOw, long codeO, Date dateStartO) {
       this.idOw = idOw;
       this.codeO = codeO;
       this.dateStartO = dateStartO;
    }
   
    public String getIdOw() {
        return this.idOw;
    }
    
    public void setIdOw(String idOw) {
        this.idOw = idOw;
    }
    public long getCodeO() {
        return this.codeO;
    }
    
    public void setCodeO(long codeO) {
        this.codeO = codeO;
    }
    public Date getDateStartO() {
        return this.dateStartO;
    }
    
    public void setDateStartO(Date dateStartO) {
        this.dateStartO = dateStartO;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AllocateOId) ) return false;
		 AllocateOId castOther = ( AllocateOId ) other; 
         
		 return ( (this.getIdOw()==castOther.getIdOw()) || ( this.getIdOw()!=null && castOther.getIdOw()!=null && this.getIdOw().equals(castOther.getIdOw()) ) )
 && (this.getCodeO()==castOther.getCodeO())
 && ( (this.getDateStartO()==castOther.getDateStartO()) || ( this.getDateStartO()!=null && castOther.getDateStartO()!=null && this.getDateStartO().equals(castOther.getDateStartO()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdOw() == null ? 0 : this.getIdOw().hashCode() );
         result = 37 * result + (int) this.getCodeO();
         result = 37 * result + ( getDateStartO() == null ? 0 : this.getDateStartO().hashCode() );
         return result;
   }   


}


