package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Car generated by hbm2java
 */
public class Car  implements java.io.Serializable {


     private int idC;
     private Location location;
     private Services services;
     private String registration;
     private String model;
     private String brand;
     private String statusCar;
     private Set<AllocateC> allocateCs = new HashSet<AllocateC>(0);

    public Car() {
    }

	
    public Car(int idC, Location location, Services services, String statusCar) {
        this.idC = idC;
        this.location = location;
        this.services = services;
        this.statusCar = statusCar;
    }
    public Car(int idC, Location location, Services services, String registration, String model, String brand, String statusCar, Set<AllocateC> allocateCs) {
       this.idC = idC;
       this.location = location;
       this.services = services;
       this.registration = registration;
       this.model = model;
       this.brand = brand;
       this.statusCar = statusCar;
       this.allocateCs = allocateCs;
    }
   
    public int getIdC() {
        return this.idC;
    }
    
    public void setIdC(int idC) {
        this.idC = idC;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Services getServices() {
        return this.services;
    }
    
    public void setServices(Services services) {
        this.services = services;
    }
    public String getRegistration() {
        return this.registration;
    }
    
    public void setRegistration(String registration) {
        this.registration = registration;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getStatusCar() {
        return this.statusCar;
    }
    
    public void setStatusCar(String statusCar) {
        this.statusCar = statusCar;
    }
    public Set<AllocateC> getAllocateCs() {
        return this.allocateCs;
    }
    
    public void setAllocateCs(Set<AllocateC> allocateCs) {
        this.allocateCs = allocateCs;
    }




}


