package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA



/**
 * ChargeId generated by hbm2java
 */
public class ChargeId  implements java.io.Serializable {


     private String idOw;
     private int idI;

    public ChargeId() {
    }

    public ChargeId(String idOw, int idI) {
       this.idOw = idOw;
       this.idI = idI;
    }
   
    public String getIdOw() {
        return this.idOw;
    }
    
    public void setIdOw(String idOw) {
        this.idOw = idOw;
    }
    public int getIdI() {
        return this.idI;
    }
    
    public void setIdI(int idI) {
        this.idI = idI;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChargeId) ) return false;
		 ChargeId castOther = ( ChargeId ) other; 
         
		 return ( (this.getIdOw()==castOther.getIdOw()) || ( this.getIdOw()!=null && castOther.getIdOw()!=null && this.getIdOw().equals(castOther.getIdOw()) ) )
 && (this.getIdI()==castOther.getIdI());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdOw() == null ? 0 : this.getIdOw().hashCode() );
         result = 37 * result + this.getIdI();
         return result;
   }   


}


