package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA



/**
 * Charge generated by hbm2java
 */
public class Charge  implements java.io.Serializable {


     private ChargeId id;
     private Inspector inspector;
     private Owner owner;
     private String dateC;
     private String belongsOwner;

    public Charge() {
    }

	
    public Charge(ChargeId id, Inspector inspector, Owner owner) {
        this.id = id;
        this.inspector = inspector;
        this.owner = owner;
    }
    public Charge(ChargeId id, Inspector inspector, Owner owner, String dateC, String belongsOwner) {
       this.id = id;
       this.inspector = inspector;
       this.owner = owner;
       this.dateC = dateC;
       this.belongsOwner = belongsOwner;
    }
   
    public ChargeId getId() {
        return this.id;
    }
    
    public void setId(ChargeId id) {
        this.id = id;
    }
    public Inspector getInspector() {
        return this.inspector;
    }
    
    public void setInspector(Inspector inspector) {
        this.inspector = inspector;
    }
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }
    public String getDateC() {
        return this.dateC;
    }
    
    public void setDateC(String dateC) {
        this.dateC = dateC;
    }
    public String getBelongsOwner() {
        return this.belongsOwner;
    }
    
    public void setBelongsOwner(String belongsOwner) {
        this.belongsOwner = belongsOwner;
    }




}


