package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Delivery generated by hbm2java
 */
public class Delivery  implements java.io.Serializable {


     private int idD;
     private String nameD;
     private int daysD;
     private Set<InspectDeliv> inspectDelivs = new HashSet<InspectDeliv>(0);

    public Delivery() {
    }

	
    public Delivery(int idD, int daysD) {
        this.idD = idD;
        this.daysD = daysD;
    }
    public Delivery(int idD, String nameD, int daysD, Set<InspectDeliv> inspectDelivs) {
       this.idD = idD;
       this.nameD = nameD;
       this.daysD = daysD;
       this.inspectDelivs = inspectDelivs;
    }
   
    public int getIdD() {
        return this.idD;
    }
    
    public void setIdD(int idD) {
        this.idD = idD;
    }
    public String getNameD() {
        return this.nameD;
    }
    
    public void setNameD(String nameD) {
        this.nameD = nameD;
    }
    public int getDaysD() {
        return this.daysD;
    }
    
    public void setDaysD(int daysD) {
        this.daysD = daysD;
    }
    public Set<InspectDeliv> getInspectDelivs() {
        return this.inspectDelivs;
    }
    
    public void setInspectDelivs(Set<InspectDeliv> inspectDelivs) {
        this.inspectDelivs = inspectDelivs;
    }




}


