package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Fal generated by hbm2java
 */
public class Fal  implements java.io.Serializable {


     private int idF;
     private String nameF;
     private int daysF;
     private Set<InspectFal> inspectFals = new HashSet<InspectFal>(0);

    public Fal() {
    }

	
    public Fal(int idF, int daysF) {
        this.idF = idF;
        this.daysF = daysF;
    }
    public Fal(int idF, String nameF, int daysF, Set<InspectFal> inspectFals) {
       this.idF = idF;
       this.nameF = nameF;
       this.daysF = daysF;
       this.inspectFals = inspectFals;
    }
   
    public int getIdF() {
        return this.idF;
    }
    
    public void setIdF(int idF) {
        this.idF = idF;
    }
    public String getNameF() {
        return this.nameF;
    }
    
    public void setNameF(String nameF) {
        this.nameF = nameF;
    }
    public int getDaysF() {
        return this.daysF;
    }
    
    public void setDaysF(int daysF) {
        this.daysF = daysF;
    }
    public Set<InspectFal> getInspectFals() {
        return this.inspectFals;
    }
    
    public void setInspectFals(Set<InspectFal> inspectFals) {
        this.inspectFals = inspectFals;
    }




}


