package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hostess generated by hbm2java
 */
public class Hostess  implements java.io.Serializable {


     private int idHos;
     private Location location;
     private Services services;
     private String firstNameHos;
     private String lastNameHos;
     private String phoneHos;
     private String faxHos;
     private String mobileHos;
     private String emailHos;
     private String statusHos;
     private Set<AllocateH> allocateHs = new HashSet<AllocateH>(0);

    public Hostess() {
    }

	
    public Hostess(int idHos, Location location, Services services, String statusHos) {
        this.idHos = idHos;
        this.location = location;
        this.services = services;
        this.statusHos = statusHos;
    }
    public Hostess(int idHos, Location location, Services services, String firstNameHos, String lastNameHos, String phoneHos, String faxHos, String mobileHos, String emailHos, String statusHos, Set<AllocateH> allocateHs) {
       this.idHos = idHos;
       this.location = location;
       this.services = services;
       this.firstNameHos = firstNameHos;
       this.lastNameHos = lastNameHos;
       this.phoneHos = phoneHos;
       this.faxHos = faxHos;
       this.mobileHos = mobileHos;
       this.emailHos = emailHos;
       this.statusHos = statusHos;
       this.allocateHs = allocateHs;
    }
   
    public int getIdHos() {
        return this.idHos;
    }
    
    public void setIdHos(int idHos) {
        this.idHos = idHos;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Services getServices() {
        return this.services;
    }
    
    public void setServices(Services services) {
        this.services = services;
    }
    public String getFirstNameHos() {
        return this.firstNameHos;
    }
    
    public void setFirstNameHos(String firstNameHos) {
        this.firstNameHos = firstNameHos;
    }
    public String getLastNameHos() {
        return this.lastNameHos;
    }
    
    public void setLastNameHos(String lastNameHos) {
        this.lastNameHos = lastNameHos;
    }
    public String getPhoneHos() {
        return this.phoneHos;
    }
    
    public void setPhoneHos(String phoneHos) {
        this.phoneHos = phoneHos;
    }
    public String getFaxHos() {
        return this.faxHos;
    }
    
    public void setFaxHos(String faxHos) {
        this.faxHos = faxHos;
    }
    public String getMobileHos() {
        return this.mobileHos;
    }
    
    public void setMobileHos(String mobileHos) {
        this.mobileHos = mobileHos;
    }
    public String getEmailHos() {
        return this.emailHos;
    }
    
    public void setEmailHos(String emailHos) {
        this.emailHos = emailHos;
    }
    public String getStatusHos() {
        return this.statusHos;
    }
    
    public void setStatusHos(String statusHos) {
        this.statusHos = statusHos;
    }
    public Set<AllocateH> getAllocateHs() {
        return this.allocateHs;
    }
    
    public void setAllocateHs(Set<AllocateH> allocateHs) {
        this.allocateHs = allocateHs;
    }




}


