package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA



/**
 * InspectSectionId generated by hbm2java
 */
public class InspectSectionId  implements java.io.Serializable {


     private int idS;
     private int msn;
     private int idI;

    public InspectSectionId() {
    }

    public InspectSectionId(int idS, int msn, int idI) {
       this.idS = idS;
       this.msn = msn;
       this.idI = idI;
    }
   
    public int getIdS() {
        return this.idS;
    }
    
    public void setIdS(int idS) {
        this.idS = idS;
    }
    public int getMsn() {
        return this.msn;
    }
    
    public void setMsn(int msn) {
        this.msn = msn;
    }
    public int getIdI() {
        return this.idI;
    }
    
    public void setIdI(int idI) {
        this.idI = idI;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InspectSectionId) ) return false;
		 InspectSectionId castOther = ( InspectSectionId ) other; 
         
		 return (this.getIdS()==castOther.getIdS())
 && (this.getMsn()==castOther.getMsn())
 && (this.getIdI()==castOther.getIdI());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdS();
         result = 37 * result + this.getMsn();
         result = 37 * result + this.getIdI();
         return result;
   }   


}


