package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * InspectFalId generated by hbm2java
 */
public class InspectFalId  implements java.io.Serializable {


     private int idF;
     private int msn;
     private int idI;
     private int idL;
     private Date dateStartF;

    public InspectFalId() {
    }

    public InspectFalId(int idF, int msn, int idI, int idL, Date dateStartF) {
       this.idF = idF;
       this.msn = msn;
       this.idI = idI;
       this.idL = idL;
       this.dateStartF = dateStartF;
    }
   
    public int getIdF() {
        return this.idF;
    }
    
    public void setIdF(int idF) {
        this.idF = idF;
    }
    public int getMsn() {
        return this.msn;
    }
    
    public void setMsn(int msn) {
        this.msn = msn;
    }
    public int getIdI() {
        return this.idI;
    }
    
    public void setIdI(int idI) {
        this.idI = idI;
    }
    public int getIdL() {
        return this.idL;
    }
    
    public void setIdL(int idL) {
        this.idL = idL;
    }
    public Date getDateStartF() {
        return this.dateStartF;
    }
    
    public void setDateStartF(Date dateStartF) {
        this.dateStartF = dateStartF;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InspectFalId) ) return false;
		 InspectFalId castOther = ( InspectFalId ) other; 
         
		 return (this.getIdF()==castOther.getIdF())
 && (this.getMsn()==castOther.getMsn())
 && (this.getIdI()==castOther.getIdI())
 && (this.getIdL()==castOther.getIdL())
 && ( (this.getDateStartF()==castOther.getDateStartF()) || ( this.getDateStartF()!=null && castOther.getDateStartF()!=null && this.getDateStartF().equals(castOther.getDateStartF()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdF();
         result = 37 * result + this.getMsn();
         result = 37 * result + this.getIdI();
         result = 37 * result + this.getIdL();
         result = 37 * result + ( getDateStartF() == null ? 0 : this.getDateStartF().hashCode() );
         return result;
   }   


}


