package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * InspectDeliv generated by hbm2java
 */
public class InspectDeliv  implements java.io.Serializable {


     private InspectDelivId id;
     private Inspector inspector;
     private Delivery delivery;
     private Aircraft aircraft;
     private Location location;
     private String statusDel;
     private String comments;
     private String mailD;
     private Date dateIns;

    public InspectDeliv() {
    }

	
    public InspectDeliv(InspectDelivId id, Inspector inspector, Delivery delivery, Aircraft aircraft, Location location, String mailD) {
        this.id = id;
        this.inspector = inspector;
        this.delivery = delivery;
        this.aircraft = aircraft;
        this.location = location;
        this.mailD = mailD;
    }
    public InspectDeliv(InspectDelivId id, Inspector inspector, Delivery delivery, Aircraft aircraft, Location location, String statusDel, String comments, String mailD, Date dateIns) {
       this.id = id;
       this.inspector = inspector;
       this.delivery = delivery;
       this.aircraft = aircraft;
       this.location = location;
       this.statusDel = statusDel;
       this.comments = comments;
       this.mailD = mailD;
       this.dateIns = dateIns;
    }
   
    public InspectDelivId getId() {
        return this.id;
    }
    
    public void setId(InspectDelivId id) {
        this.id = id;
    }
    public Inspector getInspector() {
        return this.inspector;
    }
    
    public void setInspector(Inspector inspector) {
        this.inspector = inspector;
    }
    public Delivery getDelivery() {
        return this.delivery;
    }
    
    public void setDelivery(Delivery delivery) {
        this.delivery = delivery;
    }
    public Aircraft getAircraft() {
        return this.aircraft;
    }
    
    public void setAircraft(Aircraft aircraft) {
        this.aircraft = aircraft;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getStatusDel() {
        return this.statusDel;
    }
    
    public void setStatusDel(String statusDel) {
        this.statusDel = statusDel;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getMailD() {
        return this.mailD;
    }
    
    public void setMailD(String mailD) {
        this.mailD = mailD;
    }
    public Date getDateIns() {
        return this.dateIns;
    }
    
    public void setDateIns(Date dateIns) {
        this.dateIns = dateIns;
    }




}


