package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * InspectDelivId generated by hbm2java
 */
public class InspectDelivId  implements java.io.Serializable {


     private int idD;
     private int idI;
     private int msn;
     private int idL;
     private Date datedev;

    public InspectDelivId() {
    }

    public InspectDelivId(int idD, int idI, int msn, int idL, Date datedev) {
       this.idD = idD;
       this.idI = idI;
       this.msn = msn;
       this.idL = idL;
       this.datedev = datedev;
    }
   
    public int getIdD() {
        return this.idD;
    }
    
    public void setIdD(int idD) {
        this.idD = idD;
    }
    public int getIdI() {
        return this.idI;
    }
    
    public void setIdI(int idI) {
        this.idI = idI;
    }
    public int getMsn() {
        return this.msn;
    }
    
    public void setMsn(int msn) {
        this.msn = msn;
    }
    public int getIdL() {
        return this.idL;
    }
    
    public void setIdL(int idL) {
        this.idL = idL;
    }
    public Date getDatedev() {
        return this.datedev;
    }
    
    public void setDatedev(Date datedev) {
        this.datedev = datedev;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InspectDelivId) ) return false;
		 InspectDelivId castOther = ( InspectDelivId ) other; 
         
		 return (this.getIdD()==castOther.getIdD())
 && (this.getIdI()==castOther.getIdI())
 && (this.getMsn()==castOther.getMsn())
 && (this.getIdL()==castOther.getIdL())
 && ( (this.getDatedev()==castOther.getDatedev()) || ( this.getDatedev()!=null && castOther.getDatedev()!=null && this.getDatedev().equals(castOther.getDatedev()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdD();
         result = 37 * result + this.getIdI();
         result = 37 * result + this.getMsn();
         result = 37 * result + this.getIdL();
         result = 37 * result + ( getDatedev() == null ? 0 : this.getDatedev().hashCode() );
         return result;
   }   


}


