package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * InspectSection generated by hbm2java
 */
public class InspectSection  implements java.io.Serializable {


     private InspectSectionId id;
     private Inspector inspector;
     private Aircraft aircraft;
     private Section section;
     private String statusSect;
     private Date dateStartS;
     private Date dateEndS;
     private Date dateProdStart;
     private Date dateProdEnd;
     private String comments;
     private String mailS;
     private Date dateIns;

    public InspectSection() {
    }

	
    public InspectSection(InspectSectionId id, Inspector inspector, Aircraft aircraft, Section section) {
        this.id = id;
        this.inspector = inspector;
        this.aircraft = aircraft;
        this.section = section;
    }
    public InspectSection(InspectSectionId id, Inspector inspector, Aircraft aircraft, Section section, String statusSect, Date dateStartS, Date dateEndS, Date dateProdStart, Date dateProdEnd, String comments, String mailS, Date dateIns) {
       this.id = id;
       this.inspector = inspector;
       this.aircraft = aircraft;
       this.section = section;
       this.statusSect = statusSect;
       this.dateStartS = dateStartS;
       this.dateEndS = dateEndS;
       this.dateProdStart = dateProdStart;
       this.dateProdEnd = dateProdEnd;
       this.comments = comments;
       this.mailS = mailS;
       this.dateIns = dateIns;
    }
   
    public InspectSectionId getId() {
        return this.id;
    }
    
    public void setId(InspectSectionId id) {
        this.id = id;
    }
    public Inspector getInspector() {
        return this.inspector;
    }
    
    public void setInspector(Inspector inspector) {
        this.inspector = inspector;
    }
    public Aircraft getAircraft() {
        return this.aircraft;
    }
    
    public void setAircraft(Aircraft aircraft) {
        this.aircraft = aircraft;
    }
    public Section getSection() {
        return this.section;
    }
    
    public void setSection(Section section) {
        this.section = section;
    }
    public String getStatusSect() {
        return this.statusSect;
    }
    
    public void setStatusSect(String statusSect) {
        this.statusSect = statusSect;
    }
    public Date getDateStartS() {
        return this.dateStartS;
    }
    
    public void setDateStartS(Date dateStartS) {
        this.dateStartS = dateStartS;
    }
    public Date getDateEndS() {
        return this.dateEndS;
    }
    
    public void setDateEndS(Date dateEndS) {
        this.dateEndS = dateEndS;
    }
    public Date getDateProdStart() {
        return this.dateProdStart;
    }
    
    public void setDateProdStart(Date dateProdStart) {
        this.dateProdStart = dateProdStart;
    }
    public Date getDateProdEnd() {
        return this.dateProdEnd;
    }
    
    public void setDateProdEnd(Date dateProdEnd) {
        this.dateProdEnd = dateProdEnd;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getMailS() {
        return this.mailS;
    }
    
    public void setMailS(String mailS) {
        this.mailS = mailS;
    }
    public Date getDateIns() {
        return this.dateIns;
    }
    
    public void setDateIns(Date dateIns) {
        this.dateIns = dateIns;
    }




}


