package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private int idL;
     private String nameL;
     private Set<Secretary> secretaries = new HashSet<Secretary>(0);
     private Set<Section> sections = new HashSet<Section>(0);
     private Set<InspectFal> inspectFals = new HashSet<InspectFal>(0);
     private Set<Car> cars = new HashSet<Car>(0);
     private Set<Office> offices = new HashSet<Office>(0);
     private Set<InspectDeliv> inspectDelivs = new HashSet<InspectDeliv>(0);
     private Set<Hostess> hostesses = new HashSet<Hostess>(0);

    public Location() {
    }

	
    public Location(int idL) {
        this.idL = idL;
    }
    public Location(int idL, String nameL, Set<Secretary> secretaries, Set<Section> sections, Set<InspectFal> inspectFals, Set<Car> cars, Set<Office> offices, Set<InspectDeliv> inspectDelivs, Set<Hostess> hostesses) {
       this.idL = idL;
       this.nameL = nameL;
       this.secretaries = secretaries;
       this.sections = sections;
       this.inspectFals = inspectFals;
       this.cars = cars;
       this.offices = offices;
       this.inspectDelivs = inspectDelivs;
       this.hostesses = hostesses;
    }
   
    public int getIdL() {
        return this.idL;
    }
    
    public void setIdL(int idL) {
        this.idL = idL;
    }
    public String getNameL() {
        return this.nameL;
    }
    
    public void setNameL(String nameL) {
        this.nameL = nameL;
    }
    public Set<Secretary> getSecretaries() {
        return this.secretaries;
    }
    
    public void setSecretaries(Set<Secretary> secretaries) {
        this.secretaries = secretaries;
    }
    public Set<Section> getSections() {
        return this.sections;
    }
    
    public void setSections(Set<Section> sections) {
        this.sections = sections;
    }
    public Set<InspectFal> getInspectFals() {
        return this.inspectFals;
    }
    
    public void setInspectFals(Set<InspectFal> inspectFals) {
        this.inspectFals = inspectFals;
    }
    public Set<Car> getCars() {
        return this.cars;
    }
    
    public void setCars(Set<Car> cars) {
        this.cars = cars;
    }
    public Set<Office> getOffices() {
        return this.offices;
    }
    
    public void setOffices(Set<Office> offices) {
        this.offices = offices;
    }
    public Set<InspectDeliv> getInspectDelivs() {
        return this.inspectDelivs;
    }
    
    public void setInspectDelivs(Set<InspectDeliv> inspectDelivs) {
        this.inspectDelivs = inspectDelivs;
    }
    public Set<Hostess> getHostesses() {
        return this.hostesses;
    }
    
    public void setHostesses(Set<Hostess> hostesses) {
        this.hostesses = hostesses;
    }




}


