package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Office generated by hbm2java
 */
public class Office  implements java.io.Serializable {


     private long codeO;
     private Location location;
     private Services services;
     private String building;
     private String statusOff;
     private Set<AllocateO> allocateOs = new HashSet<AllocateO>(0);

    public Office() {
    }

	
    public Office(long codeO, Location location, Services services, String statusOff) {
        this.codeO = codeO;
        this.location = location;
        this.services = services;
        this.statusOff = statusOff;
    }
    public Office(long codeO, Location location, Services services, String building, String statusOff, Set<AllocateO> allocateOs) {
       this.codeO = codeO;
       this.location = location;
       this.services = services;
       this.building = building;
       this.statusOff = statusOff;
       this.allocateOs = allocateOs;
    }
   
    public long getCodeO() {
        return this.codeO;
    }
    
    public void setCodeO(long codeO) {
        this.codeO = codeO;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Services getServices() {
        return this.services;
    }
    
    public void setServices(Services services) {
        this.services = services;
    }
    public String getBuilding() {
        return this.building;
    }
    
    public void setBuilding(String building) {
        this.building = building;
    }
    public String getStatusOff() {
        return this.statusOff;
    }
    
    public void setStatusOff(String statusOff) {
        this.statusOff = statusOff;
    }
    public Set<AllocateO> getAllocateOs() {
        return this.allocateOs;
    }
    
    public void setAllocateOs(Set<AllocateO> allocateOs) {
        this.allocateOs = allocateOs;
    }




}


