package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Secretary generated by hbm2java
 */
public class Secretary  implements java.io.Serializable {


     private int idSec;
     private Location location;
     private Services services;
     private String firstNameSec;
     private String lastNameSec;
     private String phoneSec;
     private String faxSec;
     private String mobileSec;
     private String emailSec;
     private String statusSec;
     private Set<AllocateS> allocateSs = new HashSet<AllocateS>(0);

    public Secretary() {
    }

	
    public Secretary(int idSec, Location location, Services services, String statusSec) {
        this.idSec = idSec;
        this.location = location;
        this.services = services;
        this.statusSec = statusSec;
    }
    public Secretary(int idSec, Location location, Services services, String firstNameSec, String lastNameSec, String phoneSec, String faxSec, String mobileSec, String emailSec, String statusSec, Set<AllocateS> allocateSs) {
       this.idSec = idSec;
       this.location = location;
       this.services = services;
       this.firstNameSec = firstNameSec;
       this.lastNameSec = lastNameSec;
       this.phoneSec = phoneSec;
       this.faxSec = faxSec;
       this.mobileSec = mobileSec;
       this.emailSec = emailSec;
       this.statusSec = statusSec;
       this.allocateSs = allocateSs;
    }
   
    public int getIdSec() {
        return this.idSec;
    }
    
    public void setIdSec(int idSec) {
        this.idSec = idSec;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Services getServices() {
        return this.services;
    }
    
    public void setServices(Services services) {
        this.services = services;
    }
    public String getFirstNameSec() {
        return this.firstNameSec;
    }
    
    public void setFirstNameSec(String firstNameSec) {
        this.firstNameSec = firstNameSec;
    }
    public String getLastNameSec() {
        return this.lastNameSec;
    }
    
    public void setLastNameSec(String lastNameSec) {
        this.lastNameSec = lastNameSec;
    }
    public String getPhoneSec() {
        return this.phoneSec;
    }
    
    public void setPhoneSec(String phoneSec) {
        this.phoneSec = phoneSec;
    }
    public String getFaxSec() {
        return this.faxSec;
    }
    
    public void setFaxSec(String faxSec) {
        this.faxSec = faxSec;
    }
    public String getMobileSec() {
        return this.mobileSec;
    }
    
    public void setMobileSec(String mobileSec) {
        this.mobileSec = mobileSec;
    }
    public String getEmailSec() {
        return this.emailSec;
    }
    
    public void setEmailSec(String emailSec) {
        this.emailSec = emailSec;
    }
    public String getStatusSec() {
        return this.statusSec;
    }
    
    public void setStatusSec(String statusSec) {
        this.statusSec = statusSec;
    }
    public Set<AllocateS> getAllocateSs() {
        return this.allocateSs;
    }
    
    public void setAllocateSs(Set<AllocateS> allocateSs) {
        this.allocateSs = allocateSs;
    }




}


