package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Section generated by hbm2java
 */
public class Section  implements java.io.Serializable {


     private int idS;
     private Location location;
     private String nameS;
     private int daysS;
     private Set<InspectSection> inspectSections = new HashSet<InspectSection>(0);

    public Section() {
    }

	
    public Section(int idS, Location location, int daysS) {
        this.idS = idS;
        this.location = location;
        this.daysS = daysS;
    }
    public Section(int idS, Location location, String nameS, int daysS, Set<InspectSection> inspectSections) {
       this.idS = idS;
       this.location = location;
       this.nameS = nameS;
       this.daysS = daysS;
       this.inspectSections = inspectSections;
    }
   
    public int getIdS() {
        return this.idS;
    }
    
    public void setIdS(int idS) {
        this.idS = idS;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getNameS() {
        return this.nameS;
    }
    
    public void setNameS(String nameS) {
        this.nameS = nameS;
    }
    public int getDaysS() {
        return this.daysS;
    }
    
    public void setDaysS(int daysS) {
        this.daysS = daysS;
    }
    public Set<InspectSection> getInspectSections() {
        return this.inspectSections;
    }
    
    public void setInspectSections(Set<InspectSection> inspectSections) {
        this.inspectSections = inspectSections;
    }




}


