package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Services generated by hbm2java
 */
public class Services  implements java.io.Serializable {


     private int idServ;
     private String nameServ;
     private Set<Secretary> secretaries = new HashSet<Secretary>(0);
     private Set<Office> offices = new HashSet<Office>(0);
     private Set<Hostess> hostesses = new HashSet<Hostess>(0);
     private Set<Car> cars = new HashSet<Car>(0);

    public Services() {
    }

	
    public Services(int idServ) {
        this.idServ = idServ;
    }
    public Services(int idServ, String nameServ, Set<Secretary> secretaries, Set<Office> offices, Set<Hostess> hostesses, Set<Car> cars) {
       this.idServ = idServ;
       this.nameServ = nameServ;
       this.secretaries = secretaries;
       this.offices = offices;
       this.hostesses = hostesses;
       this.cars = cars;
    }
   
    public int getIdServ() {
        return this.idServ;
    }
    
    public void setIdServ(int idServ) {
        this.idServ = idServ;
    }
    public String getNameServ() {
        return this.nameServ;
    }
    
    public void setNameServ(String nameServ) {
        this.nameServ = nameServ;
    }
    public Set<Secretary> getSecretaries() {
        return this.secretaries;
    }
    
    public void setSecretaries(Set<Secretary> secretaries) {
        this.secretaries = secretaries;
    }
    public Set<Office> getOffices() {
        return this.offices;
    }
    
    public void setOffices(Set<Office> offices) {
        this.offices = offices;
    }
    public Set<Hostess> getHostesses() {
        return this.hostesses;
    }
    
    public void setHostesses(Set<Hostess> hostesses) {
        this.hostesses = hostesses;
    }
    public Set<Car> getCars() {
        return this.cars;
    }
    
    public void setCars(Set<Car> cars) {
        this.cars = cars;
    }




}


