package Work;
// Generated 31 mars 2012 07:45:37 by Hibernate Tools 3.2.1.GA



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int idU;
     private String profilU;
     private String loginU;
     private String passwordU;

    public Users() {
    }

	
    public Users(int idU) {
        this.idU = idU;
    }
    public Users(int idU, String profilU, String loginU, String passwordU) {
       this.idU = idU;
       this.profilU = profilU;
       this.loginU = loginU;
       this.passwordU = passwordU;
    }
   
    public int getIdU() {
        return this.idU;
    }
    
    public void setIdU(int idU) {
        this.idU = idU;
    }
    public String getProfilU() {
        return this.profilU;
    }
    
    public void setProfilU(String profilU) {
        this.profilU = profilU;
    }
    public String getLoginU() {
        return this.loginU;
    }
    
    public void setLoginU(String loginU) {
        this.loginU = loginU;
    }
    public String getPasswordU() {
        return this.passwordU;
    }
    
    public void setPasswordU(String passwordU) {
        this.passwordU = passwordU;
    }




}


